# Generated by config_brpc.sh, don't modify manually
SYSTEM=Linux
HDRS=/usr/include/ /usr/local/include/
LIBS=/usr/lib64 /usr/local/lib
PROTOC=
PROTOBUF_HDR=/usr/local/include/
CC=gcc
CXX=g++
GCC_VERSION=80500
STATIC_LINKINGS= -lgflags -lprotobuf
DYNAMIC_LINKINGS=-lpthread -lssl -lcrypto -ldl -lz -lrt -lleveldb
CPPFLAGS=-DBRPC_WITH_GLOG=0 -DGFLAGS_NS=google -D__const__=__unused__ -g
# without the flag, linux+arm64 may crash due to folding on TLS.
ifeq ($(CC),gcc)
  ifeq ($(shell uname -p),aarch64) 
    CPPFLAGS+=-fno-gcse
  endif
endif

ifeq ($(NEED_LIBPROTOC), 1)
    STATIC_LINKINGS+=-lprotoc
endif
ifeq ($(NEED_GPERFTOOLS), 1)
    DYNAMIC_LINKINGS+=-ltcmalloc_and_profiler
endif
ifeq ($(NEED_GTEST), 1)
    $(error "Fail to find gtest")
endif
